const types = {
    COUNT_UP: 'COUNT_UP',
    COUNT_DOWN: 'COUNT_DOWN',
    INSERT_TODO: 'INSERT_TODO',
    DELETE_TODO: 'DELETE_TODO',
    CLEAR_TODO: 'CLEAR_TODO',
    PRESS_TODO: 'PRESS_TODO',
    SELECT_MONTHLY: 'SELECT_MONTHLY',
    SELECT_DAILY: 'SELECT_DAILY',
    SELECT_SETTING: 'SELECT_SETTING'
  };
  
  export default types;